// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dqhwbbxlnduqxxnvjipt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxaHdiYnhsbmR1cXh4bnZqaXB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNzIwOTgsImV4cCI6MjA3MTc0ODA5OH0.m6j-9MqRmhZOTky6V_Vqkw_4rY-MrE7ewau5IxpS9UE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});